# Generated by Django 4.2.1 on 2023-05-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="balance",
            field=models.IntegerField(default=0),
        ),
    ]
