# Generated by Django 4.2.1 on 2023-05-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source", "0002_alter_user_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
