# Generated by Django 4.2.1 on 2023-05-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source", "0003_game_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="image",
            field=models.ImageField(upload_to="game_images/"),
        ),
    ]
