# Generated by Django 4.2.1 on 2023-08-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source", "0015_alter_game_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="sum_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
