# Generated by Django 4.2.1 on 2023-08-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source", "0016_order_sum_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
