version: '3'

services:
  django:
    build:
      context: ../CourseSell20  # Укажите путь к вашему Django-приложению
    ports:
      - "8000:8000"  # Прокидываем порт Django на хост машины
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - DJANGO_SETTINGS_MODULE=CourseSell20.settings
    command: python manage.py runserver 0.0.0.0:8000  # Запуск Django приложения

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: GameShop
      POSTGRES_USER: GameShop
      POSTGRES_PASSWORD: 4sqyX8
    volumes:
      - "db:/var/lib/postgresql/data"

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: Slappy
      RABBITMQ_DEFAULT_PASS: V6NzmqP1
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"

volumes:
  db:
  rabbitmq_data:
