version: '3'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: GameShop
      POSTGRES_USER: GameShop
      POSTGRES_PASSWORD: 4sqyX8
    volumes:
      - "db:/var/lib/postgresql/data"

  rabbitmq:
    image: "rabbitmq:management"  # Используем образ с веб-интерфейсом управления
    ports:
      - "5672:5672"  # Порт для AMQP
      - "15672:15672"  # Порт для веб-интерфейса
    environment:
      RABBITMQ_DEFAULT_USER: Slappy  # Замените на свои значения
      RABBITMQ_DEFAULT_PASS: V6NzmqP1  # Замените на свои значения
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"

volumes:
  db:
  rabbitmq_data:
