pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Получаем исходный код проекта
                checkout scm
            }
        }

        stage('Build and Test') {
            steps {
                script {
                    def workspaceDir = pwd() // Получаем текущую директорию
                    def dockerComposeFile = "${workspaceDir}/docker-compose.yml"
                    sh "cd ${workspaceDir} && docker-compose -f ${dockerComposeFile} build"
                    // Другие шаги сборки и тестирования
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    def workspaceDir = pwd() // Получаем текущую директорию
                    def dockerComposeFile = "${workspaceDir}/path/to/your/docker-compose.yml"
                    sh "cd ${workspaceDir} && docker-compose -f ${dockerComposeFile} up -d --build"
                    // Другие шаги развертывания
                }
            }
        }
    }
}
