pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Получаем исходный код проекта
                checkout scm
            }
        }

        stage('Build and Test') {
            steps {
                script {
                    def workspaceDir = pwd() // Получаем текущую директорию
                    def dockerComposeFile = "${workspaceDir}/CourseSell20/docker-compose.yml"
                    sh "cd ${workspaceDir} && docker-compose -f ${dockerComposeFile} build"

                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    def workspaceDir = pwd() // Получаем текущую директорию
                    def dockerComposeFile = "${workspaceDir}/CourseSell20/docker-compose.yml"
                    sh "cd ${workspaceDir} && docker-compose -f ${dockerComposeFile} up -d --build"

                }
            }
        }
    }
}
