pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build and Test') {
            steps {
                sh 'docker-compose build' // Сборка Docker-контейнеров
                sh 'docker-compose up -d'  // Запуск контейнеров в фоновом режиме
                sh 'docker-compose exec django python manage.py migrate'
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker-compose down' // Остановка контейнеров
                sh 'docker-compose up -d' // Повторный запуск контейнеров
            }
        }
    }
}
